XML_WS_AgencyApp/Controllers/AgentController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using XML_WS_AgencyApp.Helpers;
using XML_WS_AgencyApp.Models;
using XML_WS_AgencyApp.Models_DTO;

namespace XML_WS_AgencyApp.Controllers
{
    public class AgentController : Controller
    {
        // GET: AgentPage
        public ActionResult AgentPage()
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
                return View();
        }

        // GET: AddNewBookingUnit
        public ActionResult AddNewBookingUnit()
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                var repo = new BookingUnitRepository();
                var model = repo.CreateBookingUnitViewModel();
                return View(model);
            }                
        }

        [HttpGet]
        public ActionResult GetCitiesByCountryId(string countryId)
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                if(!string.IsNullOrWhiteSpace(countryId))
                {
                    var repo = new CitiesRepository();
                    IEnumerable<SelectListItem> cities = repo.GetCities(countryId);
                    return Json(cities, JsonRequestBehavior.AllowGet);
                }
                else
                    return null;
            }
        }

        // GET: MyBookingUnits
        public ActionResult MyBookingUnits()
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                var repo = new BookingUnitRepository();
                long currentUserId = User.Identity.GetUserId<long>();
                var model = repo.GetMyBookingUnitsDisplayViewModel(currentUserId);
                return View(model);
            }
        }

        // GET: ManageMonthlyPrices
        public ActionResult ManageMonthlyPrices(long bookingUnitId)
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                var model = new MonthlyPricesViewModel();
                model.BookingUnitId = bookingUnitId;
                return View(model);
            }
        }

        // GET: LocalReservation
        public ActionResult LocalReservation(long bookingUnitId)
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                BookingUnitsDisplayRepo budRepo = new BookingUnitsDisplayRepo();
                var model = new LocalReservationViewModel();
                model.BookingUnitId = bookingUnitId;
                model.BookingUnitName = budRepo.GetBookingUnitNameById(bookingUnitId);
                model.DateFrom = DateTime.Now;
                model.DateTo = DateTime.Now;
                return View(model);
            }
        }

        // GET: ClientMessaging
        public ActionResult ClientMessaging()
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                MessagesDisplayRepo msgdRepo = new MessagesDisplayRepo();
                long currentUserId = User.Identity.GetUserId<long>();
                var model = new ClientMessagingViewModel();
                model.ReceivedMessages = msgdRepo.GetMessages(currentUserId);
                return View(model);
            }
        }

        // GET: OpenMessage
        public ActionResult OpenMessage(long messageId)
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                MessagesDisplayRepo msgdRepo = new MessagesDisplayRepo();
                long currentUserId = User.Identity.GetUserId<long>();
                OpenedMessageViewModel model = msgdRepo.GetOpennedMessage(messageId);
                return View(model);
            }
        }

        // GET: MyReservations
        public ActionResult MyReservations()
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                ReservationsRepository resRepo = new ReservationsRepository();
                DisplayReservationsViewModel model = new DisplayReservationsViewModel();
                long currentUserId = User.Identity.GetUserId<long>();
                model.MyReservations = resRepo.GetReservations(currentUserId);
                return View(model);
            }
        }

        public ActionResult AddBookingUnit(AddNewBookingUnitViewModel anbuVM)
        {
            if (!Request.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            else
            {
                if(ModelState.IsValid)
                {
                    DTOHelper dtoHlp = new DTOHelper();
                    bool imgValidation = dtoHlp.ValidateImageTypes(anbuVM.Images);

                    if(imgValidation)
                    {
                        List<byte[]> imagesCopy = new List<byte[]>();
                        foreach (var img in anbuVM.Images)
                        {
                            MemoryStream target = new MemoryStream();
                            img.InputStream.CopyTo(target);
                            byte[] data = target.ToArray();
                            imagesCopy.Add(data);
                        }

                        long curentUserId = User.Identity.GetUserId<long>();

                        //send a request on the main server and await for the response
                        MyRemoteServices.AgentEndpointPortClient aepc = new MyRemoteServices.AgentEndpointPortClient();
                        MyRemoteServices.addBookingUnitRequest abuRequest = dtoHlp.GetBookingUnitRequest(anbuVM, curentUserId, imagesCopy);
                        MyRemoteServices.addBookingUnitResponse abuResponse = aepc.addBookingUnit(abuRequest);


                        if (abuResponse.responseWrapper.success)
                        {
                            //save localy
                            using (var ctx = new ApplicationDbContext())
                            {
                                //create a new booking unit with all the prerequisits
                                City myCity = ctx.Cities.FirstOrDefault(x => x.Id.ToString() == anbuVM.CityId);
                                ApplicationUser agentUsr = ctx.Users.FirstOrDefault(x => x.Id == curentUserId);
                                AccomodationType myAccType = ctx.AccomodationTypes.FirstOrDefault(x => x.Id.ToString() == anbuVM.AccomodationTypeId);
                                AccomodationCategory myAccCat = ctx.AccomodationCategories.FirstOrDefault(x => x.Id.ToString() == anbuVM.AccomodationCategoryId);

                                ICollection<BonusFeatures> myBonusFeatures = new List<BonusFeatures>();
                                if(anbuVM.BonusFeatures != null)
                                {
                                    foreach (var bfvm in anbuVM.BonusFeatures)
                                    {
                                        if (bfvm.IsSelected)
                                        {
                                            var myBFeature = ctx.BonusFeatures.FirstOrDefault(x => x.Id == bfvm.Id);
                                            if (myBFeature != null)
                                                myBonusFeatures.Add(myBFeature);
                                        }
                                    }
                                }

                                BookingUnit newUnit = new BookingUnit
                                {
                                    Name = anbuVM.Name,
                                    Address = anbuVM.Address,
                                    City = myCity,
                                    Description = anbuVM.Description,
                                    PeopleNo = anbuVM.PeopleNo,
                                    Agent = agentUsr,
                                    AccomodationType = myAccType,
                                    AccomodationCategory = myAccCat,
                                    BonusFeatures = myBonusFeatures,
                                    MainServerId = (long?)abuResponse.responseWrapper.responseBody
                                };

                                //add the new unit to the DBContext
                                ctx.BookingUnits.Add(newUnit);

                                //get uploaded images and save them on the server
                                var uploadDir = "~/uploadedImages";
                                var cnt = 0;
                                foreach (var imgUpl in anbuVM.Images)
                                {
                                    string newFileName = string.Concat(Path.GetFileNameWithoutExtension(imgUpl.FileName)
                                                                , DateTime.Now.ToString("_yyyy_MM_dd_HH_mm_ss")
                                                                    , Path.GetExtension(imgUpl.FileName)
                                                                        );
                                    var imagePath = Path.Combine(Server.MapPath(uploadDir), newFileName);

                                    System.IO.File.WriteAllBytes(imagePath, imagesCopy[cnt].ToArray());

                                    var imageUrl = Path.Combine(uploadDir, newFileName);

XML_WS_AgencyApp/Views/Agent/AddNewBookingUnit.cshtml
@model XML_WS_AgencyApp.Models.AddNewBookingUnitViewModel
@{
    ViewBag.Title = "Add new booking unit";
}

<h2 style="color:#757575">Add new booking unit:</h2>

@if (TempData["error"] != null)
{
    <div id="errorId" class="row">
        <h3 style="color:#D32F2F">@TempData["error"]</h3>
    </div>
}

@using (Html.BeginForm("AddBookingUnit", "Agent", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <hr />
    <form class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Name</label>
                    <div class="col-xs-9">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Country</label>
                    <div class="col-xs-9">
                        @Html.DropDownListFor(m => Model.CountryId, new SelectList(Model.CountriesList, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "Country" })
                        @Html.ValidationMessageFor(m => m.CountryId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">City</label>
                    <div class="col-xs-9">
                        @Html.DropDownListFor(m => Model.CityId, new SelectList(Model.CitiesList, "Value", "Text"), htmlAttributes: new { @class = "form-control", @id = "City" })
                        @Html.ValidationMessageFor(m => m.CityId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Address</label>
                    <div class="col-xs-9">
                        @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Description</label>
                    <div class="col-xs-9">
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Guest capacity</label>
                    <div class="col-xs-9">
                        @Html.TextBoxFor(m => m.PeopleNo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PeopleNo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Accomodation type</label>
                    <div class="col-xs-9">
                        @Html.DropDownListFor(m => Model.AccomodationTypeId, new SelectList(Model.AccomodationTypesList, "Value", "Text"), htmlAttributes: new { @class = "form-control"})
                        @Html.ValidationMessageFor(m => m.AccomodationTypeId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Accomodation category</label>
                    <div class="col-xs-9">
                        @Html.DropDownListFor(m => Model.AccomodationCategoryId, new SelectList(Model.AccomodationCategoriesList, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.AccomodationCategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Images</label>
                    <div class="col-xs-9">
                        @Html.TextBoxFor(m => m.Images, new { @type = "file", @multiple = "multiple", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Images, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <h3 class="control-label col-xs-5" style="color:#757575">Bonus features:</h3>
                    <div class="col-xs-7"></div>
                </div>
            </div>
        </div>
        @for (int i = 0; i < Model.BonusFeatures.Count; i++)
        {
            <div class="row">
                <div class="col-sm-5">
                    <div class="form-group">
                        <label class="col-xs-6" style="color:#444444; text-align:right">@Model.BonusFeatures[i].Name</label>
                        <div class="col-xs-6">
                            @Html.CheckBoxFor(m => m.BonusFeatures[i].IsSelected)
                            @Html.HiddenFor(m => m.BonusFeatures[i].Id)
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-sm-5">
                <div class="col-xs-9"></div>
                <div class="col-xs-3">
                    <button type="submit" class="btn btn-default">Add</button>
                </div>
            </div>
        </div>
    </form>
}

@section Scripts {
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('#Country').change(function () {
            var selectedCountry = $("#Country").val();
            var citiesSelect = $('#City');
            citiesSelect.empty();
            if (selectedCountry != null && selectedCountry != '') {
                $.getJSON('@Url.Action("GetCitiesByCountryId")', { countryId: selectedCountry }, function (cities) {
                    if (cities != null && !jQuery.isEmptyObject(cities))
                    {
                        citiesSelect.append($('<option/>', {
                            value: null,
                            text: ""
                        }));
                        $.each(cities, function (index, city) {
                            citiesSelect.append($('<option/>', {
                                value: city.Value,
                                text: city.Text
                            }));
                        });
                    };
                });
            }
        });

        $(function () {
            setTimeout(function () {
                $("#errorId").hide('blind', {}, 500)
            }, 3000);
        });
    </script>
}

XML_WS_AgencyApp/Views/Agent/AgentPage.cshtml
@{
    ViewBag.Title = "Agent Page";
}

<h2 style="text-align:center;">Welcome <b style="color:#757575">@User.Identity.Name</b></h2>
<br />
<br />
<br />

@if (TempData["success"] != null)
{
    <div id="successId" class="row">
        <h3 style="color:#558B2F">@TempData["success"]</h3>
    </div>
}

<h3>Options:</h3>
<br />
<ul style="list-style-type:none">
    <li style="margin-top:10px;">@Html.ActionLink("Add new booking unit", "AddNewBookingUnit", "Agent", routeValues: null, htmlAttributes: new { @class = "btn btn-success" })</li>
    <li style="margin-top:10px;">@Html.ActionLink("Manage booking units", "MyBookingUnits", "Agent", routeValues: null, htmlAttributes: new { @class = "btn btn-warning" })</li>
    <li style="margin-top:10px;">@Html.ActionLink("Client messaging", "ClientMessaging", "Agent", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })</li>
    <li style="margin-top:10px;">@Html.ActionLink("Confirm reservations", "MyReservations", "Agent", routeValues: null, htmlAttributes: new { @class = "btn btn-danger" })</li>
</ul>

@section Scripts {
    @Scripts.Render("~/bundles/jquery-ui")

    <script type="text/javascript">
        $(function () {
            setTimeout(function () {
                $("#successId").hide('blind', {}, 500)
            }, 3000);
        });
    </script>    
}

XML_WS_AgencyApp/Views/Agent/ClientMessaging.cshtml
@model XML_WS_AgencyApp.Models.ClientMessagingViewModel
@{
    ViewBag.Title = "Client Messaging";
}

<h2 style="color:#757575">My messages:</h2>

<div style="position:relative">
    @if (Model.ReceivedMessages.Count > 0)
    {
        for (int i = 0; i < Model.ReceivedMessages.Count; i++)
        {
            if (!Model.ReceivedMessages[i].IsRead)
            {
                <div class="jumbotron" style="background-color:rgba(80,80,80,0.5);  width: 600px; margin:0 auto ">
                    <div>
                        <h2 style="color:#151515"><span style="color:#444444">Received from: </span><b>@Model.ReceivedMessages[i].SenderUserName</b></h2>
                    </div>
                    @Html.HiddenFor(m => m.ReceivedMessages[i].Id)

                    <input type="button" class="btn btn-success" value="Open" onclick="location.href='@Url.Action("OpenMessage", "Agent", new { messageId = Model.ReceivedMessages[i].Id })'" />
                </div>
                <br />
            }
            else
            {
                <div class="jumbotron" style="background-color:rgba(211,211,211,0.2);  width: 600px; margin:0 auto ">
                    <div>
                        <h2 style="color:#151515"><span style="color:#444444">Received from: </span><b>@Model.ReceivedMessages[i].SenderUserName</b></h2>
                    </div>

                    @Html.HiddenFor(m => m.ReceivedMessages[i].Id)

                    <input type="button" class="btn btn-default" value="View" onclick="location.href='@Url.Action("OpenMessage", "Agent", new { messageId = Model.ReceivedMessages[i].Id })'" />
                </div>
                <br />
            }

        }
    }
</div>

XML_WS_AgencyApp/Views/Agent/LocalReservation.cshtml
@model XML_WS_AgencyApp.Models.LocalReservationViewModel
@{
    ViewBag.Title = "Local reservation";
}

@Styles.Render("~/Content/jquery-ui/css")

<h2 style="color:#757575">Make a local reservation of the unit: <b style="color:black">@Model.BookingUnitName</b></h2>

@if (TempData["error"] != null)
{
    <div id="errorId" class="row">
        <h3 style="color:#558B2F">@TempData["error"]</h3>
    </div>
}

@using (Html.BeginForm("AddLocalReservation", "Agent", FormMethod.Post, new { @class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()
    <hr />
    <form class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.BookingUnitId)
        @Html.HiddenFor(m => m.BookingUnitName)
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Reservee first name</label>
                    <div class="col-xs-9">
                        @Html.TextBoxFor(m => m.ReserveeFirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ReserveeFirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Reservee last name</label>
                    <div class="col-xs-9">
                        @Html.TextBoxFor(m => m.ReserveeLastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ReserveeLastName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Date from</label>
                    <div class="col-xs-9">
                        @Html.TextBoxFor(m => m.DateFrom, new { @class = "date-picker" })
                        @Html.ValidationMessageFor(m => m.DateFrom, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="control-label col-xs-3" style="color:#444444">Date to</label>
                    <div class="col-xs-9">
                        @Html.TextBoxFor(m => m.DateTo, new { @class = "date-picker" })
                        @Html.ValidationMessageFor(m => m.DateTo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="col-xs-9"></div>
                <div class="col-xs-3">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </div>
    </form>
}

@section Scripts {
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/mvcfoolproof")
    <script type="text/javascript">
        $(function () {
            // This will make every element with the class "date-picker" into a DatePicker element
            $('.date-picker').datepicker();
        })

        $(function () {
            setTimeout(function () {
                $("#errorId").hide('blind', {}, 500)
            }, 3000);
        });
    </script>
}

XML_WS_AgencyApp/Views/Agent/MyBookingUnits.cshtml
@model XML_WS_AgencyApp.Models.DisplayBookingUnitsViewModel
@{
    ViewBag.Title = "My booking units";
}

<h2 style="color:#757575">My booking units:</h2>

<div style="position:relative">
    @if (Model.MyBookingUnits.Count > 0)
    {
        for (int i = 0; i < Model.MyBookingUnits.Count; i++)
        {
            <div class="jumbotron" style="background-color:rgba(211,211,211,0.2);  width: 600px; margin:0 auto ">
                <div>
                    <h2 style="color:#444444">@Model.MyBookingUnits[i].Name</h2>
                </div>
                <h3 style="font-weight:bold;color:#444444;font-size: 14px">Address: @Model.MyBookingUnits[i].Address</h3>

                <img src=@Url.Content(Model.MyBookingUnits[i].ImgUrl) height="64" width="64" />

                @Html.HiddenFor(m => m.MyBookingUnits[i].Id)

                <input type="button" class="btn btn-warning" value="Manage prices" onclick="location.href='@Url.Action("ManageMonthlyPrices", "Agent", new { bookingUnitId = Model.MyBookingUnits[i].Id })'" />
                <input type="button" class="btn btn-info" value="Local reservation" onclick="location.href='@Url.Action("LocalReservation", "Agent", new { bookingUnitId = Model.MyBookingUnits[i].Id })'" />
            </div>
            <br />
        }
    }
</div>

XML_WS_AgencyApp/Views/Agent/MyReservations.cshtml
@model XML_WS_AgencyApp.Models.DisplayReservationsViewModel
@{
    ViewBag.Title = "My reservations";
}

<h2 style="color:#757575">My reservations:</h2>

@if (TempData["error"] != null)
{
    <div id="errorId" class="row">
        <h3 style="color:#558B2F">@TempData["error"]</h3>
    </div>
}

@if (TempData["success"] != null)
{
    <div id="successId" class="row">
        <h3 style="color:#558B2F">@TempData["success"]</h3>
    </div>
}

<div style="position:relative">
    @if (Model.MyReservations.Count > 0)
    {
        for (int i = 0; i < Model.MyReservations.Count; i++)
        {
            if ((int)Model.MyReservations[i].ReservationStatus == 0)
            {
                <div class="jumbotron" style="background-color:rgba(211,211,211,0.2);  width: 600px; margin:0 auto ">
                    <div>
                        <h2 style="color:#151515"><b style="color:#616161; font-weight:700">@Model.MyReservations[i].BookingUnitName</b> reserved by <span style="color:#444444">@Model.MyReservations[i].ReserveeFullName</span></h2>
                        <img src=@Url.Content(Model.MyReservations[i].ImgUrl) height="128" width="128" />
                        <h3>From <span style="color:deepskyblue">@Model.MyReservations[i].DateFrom</span> To <span style="color:deepskyblue">@Model.MyReservations[i].DateTo</span></h3>
                    </div>
                    
                    <h2 style="color:#151515">Price: <b style="color:#000000">@Model.MyReservations[i].TotalPrice</b></h2>
                    @Html.HiddenFor(m => m.MyReservations[i].Id)
                    @if (Model.MyReservations[i].CanBeConfirmed)
                    {
                        <input type="button" class="btn btn-success" value="Confirm" onclick="location.href='@Url.Action("ConfirmReservation", "Agent", new { reservationId = Model.MyReservations[i].Id })'" />
                        <input type="button" class="btn btn-danger" value="Cancel" onclick="location.href='@Url.Action("CancelReservation", "Agent", new { reservationId = Model.MyReservations[i].Id })'" />
                    }
                </div>
                <br />
            }
            else if ((int)Model.MyReservations[i].ReservationStatus == 1)
            {
                <div class="jumbotron" style="background-color:rgba(0,230,118,0.2);  width: 600px; margin:0 auto ">
                    <div>
                        <h2 style="color:#151515"><b style="color:#616161; font-weight:700">@Model.MyReservations[i].BookingUnitName</b> reserved by <span style="color:#444444">@Model.MyReservations[i].ReserveeFullName</span></h2>
                        <img src=@Url.Content(Model.MyReservations[i].ImgUrl) height="128" width="128" />
                        <h3>From <span style="color:deepskyblue">@Model.MyReservations[i].DateFrom</span> To <span style="color:deepskyblue">@Model.MyReservations[i].DateTo</span></h3>
                    </div>

                    <h2 style="color:#151515">Price: <b style="color:#000000">@Model.MyReservations[i].TotalPrice</b></h2>

                    <h3 style="color:#1B5E20"><b style="font-weight:900">Confirmed</b></h3>
                </div>
                <br />
            }
            else
            {
                <div class="jumbotron" style="background-color:rgba(211,47,47,0.5);  width: 600px; margin:0 auto ">
                    <div>
                        <h2 style="color:#151515"><b style="color:#616161; font-weight:700">@Model.MyReservations[i].BookingUnitName</b> reserved by <span style="color:#444444">@Model.MyReservations[i].ReserveeFullName</span></h2>
                        <img src=@Url.Content(Model.MyReservations[i].ImgUrl) height="128" width="128" />
                        <h3>From <span style="color:deepskyblue">@Model.MyReservations[i].DateFrom</span> To <span style="color:deepskyblue">@Model.MyReservations[i].DateTo</span></h3>
                    </div>

                    <h2 style="color:#151515">Price: <b style="color:#000000">@Model.MyReservations[i].TotalPrice</b></h2>

                    <h3 style="color:#D50000"><b style="font-weight:900">Canceled</b></h3>
                </div>
                <br />
            }
        }
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jquery-ui")

    <script type="text/javascript">
        $(function () {
            setTimeout(function () {
                $("#errorId").hide('blind', {}, 500)
                $("#successId").hide('blind', {}, 500)
            }, 3000);
        });
    </script>
}